####1.4 Split the merged data into two part , lyrics and audio to ease the task

In [ ]:
from google.colab import drive

drive.mount('/content/drive')
project_folder_path = "/content/drive/MyDrive/TaylorSwiftEras/"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
import pandas as pd

taylor_merged_path = os.path.join(project_folder_path ,'Data/Final/taylor_merged_df.csv' )
taylor_merged_df = pd.read_csv(taylor_merged_path)
taylor_merged_df

,album_name,ep,album_release,track_number,track_name,artist,track_release,danceability,energy,key,...,liveness,valence,tempo,time_signature,duration_ms,explicit,key_name,mode_name,key_mode,lyric
0,Taylor Swift,False,2006-10-24,1.0,Tim McGraw,Taylor Swift,2006-06-19,0.580000,0.491000,0.000000,...,0.12100,0.425000,76.009000,4.00000,232107.000000,False,C,major,C major,[Verse 1] He said the way my blue eyes shined ...
1,Taylor Swift,False,2006-10-24,2.0,Picture To Burn,Taylor Swift,2006-10-24,0.658000,0.877000,7.000000,...,0.09620,0.821000,105.586000,4.00000,173067.000000,False,G,major,G major,"[Verse 1] State the obvious, I didn't get my p..."
2,Taylor Swift,False,2006-10-24,3.0,Teardrops On My Guitar,Taylor Swift,2006-10-24,0.621000,0.417000,10.000000,...,0.11900,0.289000,99.953000,4.00000,203040.000000,False,A#,major,A# major,[Verse 1] Drew looks at me I fake a smile so h...
3,Taylor Swift,False,2006-10-24,4.0,A Place In This World,Taylor Swift,2006-10-24,0.576000,0.777000,9.000000,...,0.32000,0.428000,115.028000,4.00000,199200.000000,False,A,major,A major,"[Spoken Intro] So, we're gonna have the band t..."
4,Taylor Swift,False,2006-10-24,5.0,Cold As You,Taylor Swift,2006-10-24,0.418000,0.482000,5.000000,...,0.12300,0.261000,175.558000,4.00000,239013.000000,False,F,major,F major,[Verse 1] You have a way of coming easily to m...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,Beautiful Eyes,True,2008-07-15,1.0,Beautiful Eyes,Taylor Swift,2008-07-15,0.589008,0.577084,4.676471,...,0.14089,0.407839,124.038765,3.97479,237852.592437,False,G,major,G major,[Verse 1] Your beautiful eyes Stare right into...
179,Beautiful Eyes,True,2008-07-15,2.0,Should've Said No (Alternate Version),Taylor Swift,2008-07-15,0.589008,0.577084,4.676471,...,0.14089,0.407839,124.038765,3.97479,237852.592437,False,G,major,G major,[Verse 1] It's strange to think The songs we u...
180,Beautiful Eyes,True,2008-07-15,3.0,Teardrops On My Guitar (Acoustic Version),Taylor Swift,2008-07-15,0.589008,0.577084,4.676471,...,0.14089,0.407839,124.038765,3.97479,237852.592437,False,G,major,G major,[Verse 1] Drew looks at me I fake a smile so h...
181,Beautiful Eyes,True,2008-07-15,4.0,Picture To Burn (Radio Edit),Taylor Swift,2008-07-15,0.589008,0.577084,4.676471,...,0.14089,0.407839,124.038765,3.97479,237852.592437,False,G,major,G major,"[Verse 1] State the obvious, I didn't get my p..."
182,Beautiful Eyes,True,2008-07-15,6.0,I Heart ?,Taylor Swift,2008-06-23,0.589008,0.577084,4.676471,...,0.14089,0.407839,124.038765,3.97479,237852.592437,False,G,major,G major,[Verse 1] Wish I had concentrated They said lo...

In [ ]:
taylor_lyric_df = taylor_merged_df[['album_name' , 'track_number' , 'track_name' , 'lyric']].copy()
taylor_lyric_df

,album_name,track_number,track_name,lyric
0,Taylor Swift,1.0,Tim McGraw,[Verse 1] He said the way my blue eyes shined ...
1,Taylor Swift,2.0,Picture To Burn,"[Verse 1] State the obvious, I didn't get my p..."
2,Taylor Swift,3.0,Teardrops On My Guitar,[Verse 1] Drew looks at me I fake a smile so h...
3,Taylor Swift,4.0,A Place In This World,"[Spoken Intro] So, we're gonna have the band t..."
4,Taylor Swift,5.0,Cold As You,[Verse 1] You have a way of coming easily to m...
...,...,...,...,...
178,Beautiful Eyes,1.0,Beautiful Eyes,[Verse 1] Your beautiful eyes Stare right into...
179,Beautiful Eyes,2.0,Should've Said No (Alternate Version),[Verse 1] It's strange to think The songs we u...
180,Beautiful Eyes,3.0,Teardrops On My Guitar (Acoustic Version),[Verse 1] Drew looks at me I fake a smile so h...
181,Beautiful Eyes,4.0,Picture To Burn (Radio Edit),"[Verse 1] State the obvious, I didn't get my p..."
182,Beautiful Eyes,6.0,I Heart ?,[Verse 1] Wish I had concentrated They said lo...

In [ ]:
taylor_lyric_df.to_csv(os.path.join(project_folder_path ,'Data/Final/taylor_lyric_df.csv') , index=False)
print('Successfully added file : taylor_lyric_df.csv')

Successfully added file : taylor_lyric_df.csv

In [ ]:
taylor_audio_df = taylor_merged_df[['album_name' , 'track_number' , 'track_name' , 'danceability' , 'energy',
                                    'key' , 'loudness' , 'mode' , 'speechiness' , 'acousticness' , 'instrumentalness',
                                    'liveness' , 'valence' , 'tempo' , 'time_signature' , 'duration_ms' ,
                                    'explicit' , 'key_name' , 'mode_name' , 'key_mode']].copy()
taylor_audio_df

,album_name,track_number,track_name,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,duration_ms,explicit,key_name,mode_name,key_mode
0,Taylor Swift,1.0,Tim McGraw,0.580000,0.491000,0.000000,-6.462000,1.000000,0.025100,0.575000,0.000000,0.12100,0.425000,76.009000,4.00000,232107.000000,False,C,major,C major
1,Taylor Swift,2.0,Picture To Burn,0.658000,0.877000,7.000000,-2.098000,1.000000,0.032300,0.173000,0.000000,0.09620,0.821000,105.586000,4.00000,173067.000000,False,G,major,G major
2,Taylor Swift,3.0,Teardrops On My Guitar,0.621000,0.417000,10.000000,-6.941000,1.000000,0.023100,0.288000,0.000000,0.11900,0.289000,99.953000,4.00000,203040.000000,False,A#,major,A# major
3,Taylor Swift,4.0,A Place In This World,0.576000,0.777000,9.000000,-2.881000,1.000000,0.032400,0.051000,0.000000,0.32000,0.428000,115.028000,4.00000,199200.000000,False,A,major,A major
4,Taylor Swift,5.0,Cold As You,0.418000,0.482000,5.000000,-5.769000,1.000000,0.026600,0.217000,0.000000,0.12300,0.261000,175.558000,4.00000,239013.000000,False,F,major,F major
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,Beautiful Eyes,1.0,Beautiful Eyes,0.589008,0.577084,4.676471,-7.364197,0.915966,0.053517,0.298719,0.003325,0.14089,0.407839,124.038765,3.97479,237852.592437,False,G,major,G major
179,Beautiful Eyes,2.0,Should've Said No (Alternate Version),0.589008,0.577084,4.676471,-7.364197,0.915966,0.053517,0.298719,0.003325,0.14089,0.407839,124.038765,3.97479,237852.592437,False,G,major,G major
180,Beautiful Eyes,3.0,Teardrops On My Guitar (Acoustic Version),0.589008,0.577084,4.676471,-7.364197,0.915966,0.053517,0.298719,0.003325,0.14089,0.407839,124.038765,3.97479,237852.592437,False,G,major,G major
181,Beautiful Eyes,4.0,Picture To Burn (Radio Edit),0.589008,0.577084,4.676471,-7.364197,0.915966,0.053517,0.298719,0.003325,0.14089,0.407839,124.038765,3.97479,237852.592437,False,G,major,G major
182,Beautiful Eyes,6.0,I Heart ?,0.589008,0.577084,4.676471,-7.364197,0.915966,0.053517,0.298719,0.003325,0.14089,0.407839,124.038765,3.97479,237852.592437,False,G,major,G major

In [ ]:
taylor_audio_df.to_csv(os.path.join(project_folder_path ,'Data/Final/taylor_audio_df.csv') , index=False)
print('Successfully added file : taylor_audio_df.csv')

Successfully added file : taylor_audio_df.csv